version: "0.2"
ignorePaths:
  - "*.svg"
  - _build
  - Makefile
  - .gitignore
  - _config.yml
  - _toc.yml
  - "*.xml"
dictionaryDefinitions: []
dictionaries: []
words:
  - Certus
  - ciutshi
  - interpretability
  - soo-shee
ignoreWords:
  - Angele
  - Atwal
  - autoupdate
  - Berners
  - Borgatti
  - Brickley
  - DAMA
  - Delen
  - Earley
  - Fensel
  - Gruber
  - Guha
  - Hendler
  - Huaman
  - hypergraph
  - hypergraphs
  - Karle
  - Keet
  - Kitchin
  - Ladley
  - lakehouse
  - Lassila
  - Latour
  - Leondes
  - Musen
  - Neta
  - occurrent
  - occurrents
  - ontologists
  - Panasiuk
  - RDBMS
  - Sharda
  - Simsek
  - Sowa
  - Steup
  - Sykora
  - Tahko
  - Toma
  - Umbrich
  - Wahler
  - Wasserman
  - Zalta
  - triplestore
  - DMBOK
  - deconfliction
  - embeddedness
  - socio-technical
  - enculturated
  - metametaphysics
  - dataops
  - Apress
  - actants
  - spatio-temporal
  - monohierarchy
import: []
